apiVersion: v1
kind: Pod
metadata:
  name: kafka-consumer1
spec:
  containers:
  - args:
    - bin/kafka-console-consumer.sh
    - --bootstrap-server
    - my-cluster-kafka-bootstrap:9092
    - --topic
    - my-topic1
    - --from-beginning
    image: strimzi/kafka:0.12.1-kafka-2.2.1
    imagePullPolicy: Always
    name: kafka-consumer1
    resources:
      requests:
        memory: "150Mi"
        cpu: "150m"
      limits:
        memory: "250Mi"
        cpu: "250m"
  restartPolicy: OnFailure
