apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    strimzi.io/kind: cluster
    strimzi.io/type: kafka
  name: my-cluster
data:
  kafka-config: |-
    {
      "num.partitions": 2,
      "num.recovery.threads.per.data.dir": 2,
      "default.replication.factor": 2,
      "offsets.topic.replication.factor": 2,
      "transaction.state.log.replication.factor": 2,
      "transaction.state.log.min.isr": 1,
      "log.retention.hours": 168,
      "log.segment.bytes": 1073741824,
      "log.retention.check.interval.ms": 300000,
      "num.network.threads": 3,
      "num.io.threads": 8,
      "socket.send.buffer.bytes": 102400,
      "socket.receive.buffer.bytes": 102400,
      "socket.request.max.bytes": 104857600,
      "group.initial.rebalance.delay.ms": 0
    }
  kafka-healthcheck-delay: '15'
  kafka-healthcheck-timeout: '5'
  kafka-jvmOptions: |-
    {
      "-Xmx": "256M",
      "-Xms": "256M"
    }
  kafka-nodes: '2'
  kafka-resources: |-
    {
      "requests": {
        "cpu": "200m",
        "memory": "512Mi"
      },
      "limits": {
        "cpu": "500m",
        "memory": "512Mi"
      }
    }
  kafka-storage: '{ "type": "ephemeral" }'
  topic-operator-config: |-
    {
      "resources": {
        "requests": {
          "cpu": "100m",
          "memory": "128Mi"
        },
        "limits": {
          "cpu": "1",
          "memory": "128Mi"
        }
      }
    }
  zookeeper-healthcheck-delay: '15'
  zookeeper-healthcheck-timeout: '5'
  zookeeper-nodes: '1'
  zookeeper-resources: |-
    {
      "requests": {
        "cpu": "200m",
        "memory": "128Mi"
      },
      "limits": {
        "cpu": "1",
        "memory": "128Mi"
      }
    }
  zookeeper-storage: '{ "type": "ephemeral" }'
