apiVersion: v1
kind: PersistentVolume
metadata:
  name: ubi7-pv1
  labels:
    type: local
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/Users/alexly/Desktop/test/openshift.local.clusterup/openshift.local.pv/ubi7-pv1"
  persistentVolumeReclaimPolicy: Retain
