---

- name: Manage ubi7 DeploymentConfig for CR {{ meta.name }} on project {{ meta.namespace }}
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'ubi7-deployment.yml.j2') }}"

- name: Manage ubi7 Service for CR {{ meta.name }} on project {{ meta.namespace }}
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'ubi7-service.yml.j2') }}"
