apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: <CLUSTERID>
  name: <CLUSTERID>-<ROLE>-<REGION><ZONE>
  namespace: openshift-machine-api
spec:
  replicas: <REPLICAS>
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: <CLUSTERID>
      machine.openshift.io/cluster-api-machine-role: <ROLE>
      machine.openshift.io/cluster-api-machine-type: <ROLE>
      machine.openshift.io/cluster-api-machineset: <CLUSTERID>-<ROLE>-<REGION><ZONE>
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: <CLUSTERID>
        machine.openshift.io/cluster-api-machine-role: <ROLE>
        machine.openshift.io/cluster-api-machine-type: <ROLE>
        machine.openshift.io/cluster-api-machineset: <CLUSTERID>-<ROLE>-<REGION><ZONE>
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/<ROLE>: ""
      providerSpec:
        value:
          ami:
            id: <AMIID>
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: <CLUSTERID>-worker-profile
          instanceType: m4.large
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: <ZONE>
            region: <REGION>
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - <CLUSTERID>-worker-sg
          subnet:
            filters:
              - name: tag:Name
                values:
                  - <CLUSTERID>-private-<REGION>
          tags:
            - name: kubernetes.io/cluster/<CLUSTERID>
              value: owned
          userDataSecret:
            name: worker-user-data
