---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        -
          image: "nginx:1.7.9"
          name: nginx
          ports:
            -
              containerPort: 80
          volumeMounts:
            -
              mountPath: "/usr/share/nginx/html"
              name: nginx-pv-storage
      volumes:
        -
          name: nginx-pv-storage
          persistentVolumeClaim:
            claimName: helloworld-pv1
