apiVersion: v1
baseDomain: openshiftaws.com
compute:
- hyperthreading: Enabled
  name: worker
  platform:
    aws:
      type: t3.large
  replicas: 3
controlPlane:
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 1
metadata:
  creationTimestamp: null
  name: ly-demo
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-east-2
pullSecret: <PULL_SECRET>
sshKey: <SSH_KEY>
